const IMAGES = {
    "2_red": require('./svg/2_red.svg').default,
    "3_red": require('./svg/3_red.svg').default,
    "4_red": require('./svg/4_red.svg').default,
    "5_red": require('./svg/5_red.svg').default,
    "6_red": require('./svg/6_red.svg').default,
    "7_red": require('./svg/7_red.svg').default,
    "8_red": require('./svg/8_red.svg').default,
    "9_red": require('./svg/9_red.svg').default,
    "0_red": require('./svg/10_red.svg').default,
    "J_red": require('./svg/J_red.svg').default,
    "Q_red": require('./svg/Q_red.svg').default,
    "K_red": require('./svg/K_red.svg').default,
    "A_red": require('./svg/A_red.svg').default,
    "2_black": require('./svg/2_black.svg').default,
    "3_black": require('./svg/3_black.svg').default,
    "4_black": require('./svg/4_black.svg').default,
    "5_black": require('./svg/5_black.svg').default,
    "6_black": require('./svg/6_black.svg').default,
    "7_black": require('./svg/7_black.svg').default,
    "8_black": require('./svg/8_black.svg').default,
    "9_black": require('./svg/9_black.svg').default,
    "0_black": require('./svg/10_black.svg').default,
    "J_black": require('./svg/J_black.svg').default,
    "Q_black": require('./svg/Q_black.svg').default,
    "K_black": require('./svg/K_black.svg').default,
    "A_black": require('./svg/A_black.svg').default,
    "S": require('./svg/spades.svg').default,
    "C": require('./svg/clubs.svg').default,
    "D": require('./svg/diamonds.svg').default,
    "H": require('./svg/hearts.svg').default,
    "back": require('./svg/back.svg').default,
    "solid-background": require('./svg/solid_background.svg').default
}

export default IMAGES;
